# Add your resource or module blocks here.
# Each block should be preceded by a comment with the resource display name and a link to the provider docs:
#
# # Example Resource
# # https://search.opentofu.org/provider/hashicorp/google/latest/docs/resources/RESOURCE_TYPE
#
# resource "google_example_resource" "this" {
#   labels  = var.labels
#   name    = "MODULE_SHORT_NAME-${module.core_helpers.env}"
#   project = var.project_id
# }
